package My::Store::Type::Email;

use MooseX::Types -declare => [ qw/ TypeEmailAddress / ];
use MooseX::Types::Email qw/EmailAddress/;

subtype TypeEmailAddress, 
   as EmailAddress,
   where { &email_suppresion_domain($_) and &email_suppresion_user($_) };
   message { "email_suppression_list" };

my %suppresion_domains = (
   '21box.com' => 1,
   '5xx.org' => 1,
   '852.net' => 1,
   'ac.com' => 1,
   'altavista.co.uk' => 1,
   'altavista.com' => 1,
   'altavista.de' => 1,
   'altavista.des' => 1,
   'altavista.fr' => 1,
   'angelfire' => 1,
   'asdf.nl' => 1,
   'asdf.nl' => 1,
   'attbi.com' => 1,
   'attbi.com' => 1,
   'attbi.net' => 1,
   'beseen.com' => 1,
   'bigmailbox' => 1,
   'bn3' => 1,
   'box.com' => 1,
   'chickmail' => 1,
   'cix.net' => 1,
   'cluestick.org' => 1,
   'comstar.com' => 1,
   'connactivity.com' => 1,
   'coolemail.net' => 1,
   'cyberangels.nl' => 1,
   'deadbolt.com' => 1,
   'deu.com' => 1,
   'devil.com' => 1,
   'digitalme.com' => 1,
   'dog.com' => 1,
   'dsl092-077-098.bos1.dsl.speakeasy.net' => 1,
   'dummies.com' => 1,
   'enetdec.com' => 1,
   'eorders' => 1,
   'eurosport.com' => 1,
   'exciteukmail' => 1,
   'firstnethou.com' => 1,
   'firstnethou.com' => 1,
   'firstnethou.com' => 1,
   'fishingLife' => 1,
   'freemail.nl' => 1,
   'gain-ny.com' => 1,
   'gameSpot' => 1,
   'gateway.net' => 1,
   'geekmail.com' => 1,
   'guilmette.org' => 1,
   'gulfgate.com' => 1,
   'highabove' => 1,
   'home.com' => 1,
   'home.com' => 1,
   'houston.rr.com' => 1,
   'hyperoffice.com' => 1,
   'ibm.net' => 1,
   'ih.navy.mil' => 1,
   'inbox.com' => 1,
   'inetica.com' => 1,
   'internetmci.com' => 1,
   'internetmci.net' => 1,
   'isux.com' => 1,
   'ivillage' => 1,
   'jam.rr.com' => 1,
   'jlmail' => 1,
   'jmail.co.jp' => 1,
   'joymail' => 1,
   'junglemate' => 1,
   'keftamail' => 1,
   'konzoo.coms' => 1,
   'law.com' => 1,
   'Law.com' => 1,
   'locos.com' => 1,
   'looksmart' => 1,
   'lovemail.com' => 1,
   'ltinet.com' => 1,
   'mail-abuse.com' => 1,
   'mail-abuse.net' => 1,
   'mail-abuse.org' => 1,
   'mailblocks' => 1,
   'mandarin.com' => 1,
   'maps.com' => 1,
   'maps.net' => 1,
   'maps.org' => 1,
   'masterdsl.com' => 1,
   'masterdsl.net' => 1,
   'mastipruds.org' => 1,
   'mci.net' => 1,
   'mci2000.com' => 1,
   'mcimail.com' => 1,
   'mcimail.com' => 1,
   'media1st.com' => 1,
   'mediaone.net' => 1,
   'metagram.net' => 1,
   'metagram.org' => 1,
   'metagrams.net' => 1,
   'metagrams.org' => 1,
   'midsouth.rr.com' => 1,
   'mn.rr.com' => 1,
   'mollymail' => 1,
   'momslife.com' => 1,
   'monkeys.com' => 1,
   'monkeys.com' => 1,
   'myinboxplus.com' => 1,
   'mysun' => 1,
   'n2mail' => 1,
   'nameplanet.com' => 1,
   'nanas.surriel.com' => 1,
   'netpen.net' => 1,
   'networkmci.com' => 1,
   'networkmci.net' => 1,
   'newfunandcool.com' => 1,
   'newmail.net' => 1,
   'obob.com' => 1,
   'orbs.net' => 1,
   'orbs.org' => 1,
   'otto.net' => 1,
   'paxemail.com' => 1,
   'poopypants.com' => 1,
   'pop3now' => 1,
   'postmark.net' => 1,
   'privatemail.com' => 1,
   'prodigy.com' => 1,
   'projecthoneypot.org' => 1,
   'pumapost' => 1,
   'redpaul.mfnx.net' => 1,
   'se.rr.com' => 1,
   'seebs.net' => 1,
   'smac.hensema.net' => 1,
   'sorbs.net' => 1,
   'space.com' => 1,
   'spamtrap.rangers.eu.org' => 1,
   'sport.rr.com' => 1,
   'start.com.au' => 1,
   'startrekmail.com' => 1,
   'stoned.com' => 1,
   'stopspam.org' => 1,
   'subdimension' => 1,
   'suespammers.org' => 1,
   'suite101email' => 1,
   'swfla.rr.com' => 1,
   'talkcity.com' => 1,
   'toast.com' => 1,
   'tomorrowssolution.com' => 1,
   'trap.offshoreexecutive.com' => 1,
   'ttl.pactel.com' => 1,
   'ucwphilly.rr.com' => 1,
   'us.oracle.com' => 1,
   'us.pwcglobal.com' => 1,
   'uunetuu.net' => 1,
   'valise' => 1,
   'visto/myvisto' => 1,
   'vix.com' => 1,
   'web-cyat.com' => 1,
   'webrix.net' => 1,
   'whitehat.com' => 1,
   'winuk.net' => 1,
   'worldmailer' => 1,
   'yepes.com' => 1,
   'ziplip.com' => 1,
   'zkey' => 1
);

sub email_suppresion_domain {
   my ($email) = @_;
   my ($user, $domain) = split(/\@/, $email);

   return 0 if exists $suppresion_domains{$domain};
   return 1;
}

my %suppresion_user = (
   'abuse' => 1,
   'bin' => 1,
   'dns' => 1,
   'dnsadmin' => 1,
   'domainadmin' => 1,
   'domains' => 1,
   'dsnadmin' => 1,
   'feedback' => 1,
   'ftp' => 1,
   'games' => 1,
   'guest' => 1,
   'hostmaster' => 1,
   'info' => 1,
   'listowner' => 1,
   'listserv' => 1,
   'listserver' => 1,
   'mailerdaemon' => 1,
   'news' => 1,
   'newsletter' => 1,
   'nobody' => 1,
   'noc' => 1,
   'noreply' => 1,
   'nospam' => 1,
   'operations' => 1,
   'ops' => 1,
   'orders' => 1,
   'other' => 1,
   'owner' => 1,
   'postmaster' => 1,
   'privacy' => 1,
   'root' => 1,
   'sales' => 1,
   'security' => 1,
   'service' => 1,
   'spam' => 1,
   'spamtrap' => 1,
   'subscribe' => 1,
   'support' => 1,
   'sys' => 1,
   'sysadmin' => 1,
   'systemadmin' => 1,
   'usenet' => 1,
   'uucp' => 1,
   'whois' => 1,
   'www' => 1,
   'abuse' => 1
);

sub email_suppresion_user {
   my ($email) = @_;
   my ($user, $domain) = split(/\@/, $email);
   
   return 0 if exists $suppresion_user{$user};
   return 1;
}
   
   
1;
